fastlane_version '2.228.0'
default_platform :ios

platform :ios do
# You can define global options for all lanes here
  desc 'Build project and executes unit tests'
  lane :unit_test do |options|
    run_tests(
      workspace: "GithubActionDemo.xcodeproj/project.xcworkspace",
      scheme: "GithubActionDemo",
      # device: "iPhone 14",
      # destination: "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0",
      device: "iPhone 15",
      # clean: true
      clean: options[:clean],
      skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution]
    )
  end
end
