fastlane_version '2.228.0'
default_platform :ios

platform :ios do
  desc "Runs all tests on the project"
  lane :unit_test do |options|
    scan(
      workspace: "GithubActionDemo.xcodeproj/project.xcworkspace",
      scheme: "GithubActionDemo",
      device: "iPhone 15 Pro",  # Or "iPhone SE (3rd generation)", "iPhone 14", etc.
      clean: true,
      output_directory: "fastlane/test_output",
      output_types: "junit,html"
    )
  end
end
